name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  dockerize:
    name: Dockerize
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - run: sudo apt-get -y install binutils
      - run: sudo apt-get -y install fakeroot

      - name: create version number
        shell: bash
        run: echo "VERSION=v$(date +'%Y%m%d.%H%M%S')" >> "$GITHUB_ENV"

      - uses: actions/checkout@v4

      - name: update version
        run: |
          sudo sed -i -e "s|00000000.000000|$VERSION|g" ./build.gradle
          sudo sed -i -e "s|00000000.000000|$VERSION|g" ./src/main/java/com/inspiretmstech/api/constants/Config.java
        env:
          VERSION: ${{ env.VERSION }}

      - name: login to registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: extract metadata for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.VERSION }}
            type=raw,value=latest

      - name: build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GH_USER=inspire-labs-tech-readonly
            GH_TOKEN=${{ secrets.INSPIRE_TMS_READONLY_PERSONAL_ACCESS_TOKEN }}
  types:
    name: Generate Types
    needs: dockerize
    runs-on: ubuntu-latest
    services:
      self:
        image: ghcr.io/inspire-labs-tms-tech/inspire-tms-api:latest
        ports:
          - 8080:8080
        credentials:
          username: inspire-labs-tech-readonly
          password: ${{ secrets.INSPIRE_TMS_READONLY_PERSONAL_ACCESS_TOKEN }}
    permissions:
      contents: write
      packages: write
    steps:
      - run: sudo apt-get -y install binutils
      - run: sudo apt-get -y install fakeroot
      - run: sudo apt-get -y install jq

      - name: setup
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: get the current version
        run: echo "VERSION=$(git show HEAD:version.json | jq .version --raw-output)" >> "$GITHUB_ENV"

      - name: get the previous version
        run: echo "PREVIOUS_VERSION=$(git show HEAD~1:version.json | jq .version --raw-output)" >> "$GITHUB_ENV"

      - name: check version
        shell: bash
        run: |
          if [[ "$VERSION" == "$PREVIOUS_VERSION" ]]; then
            echo "version change confirmed!";
          else
            echo "version not changed!";
            exit 1;
          fi
        env:
          VERSION: ${{ env.VERSION }}
          PREVIOUS_VERSION: ${{ env.PREVIOUS_VERSION }}

      - name: generate typescript client
        run: |
          npx --yes @hey-api/openapi-ts \
            --input http://127.0.0.1:8080/api-docs \
            --output .
          ls -la
